# Generated by Django 4.2.5 on 2023-10-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('expiration_date', models.DateTimeField()),
                ('unique_identifier', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
