# Generated by Django 4.2.5 on 2023-10-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedfile',
            name='unique_identifier',
        ),
    ]
